In [1]:
from env import *

In [2]:
numbaMain(random_player,random_player,random_player,random_player,random_player,500000,0)

(array([ 99708, 100041,  99910, 100439,  99902,      0], dtype=int64), 0)

In [3]:
env = np.array([6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 2.0, 3.0, 4.0, 0.0, 1.0, 2.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3.0, 1.0, 0.0, 0.0, 0.0, 3.0, 3.0, 3.0])
draw_pile = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 53.0])
discard_pile = np.array([6.0, 2.0, 5.0, 3.0, 2.0, 3.0, 2.0, 2.0, 0.0, 2.0, 5.0, 9.0, 4.0])

In [4]:
getValidActions(getAgentState(env,draw_pile,discard_pile))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
getAgentState(env,draw_pile,discard_pile)[67:71]

array([0., 0., 0., 1.])

In [6]:
env[67]

3.0

In [7]:
env,draw_pile,discard_pile

(array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 2., 3., 4., 0., 1., 2., 1., 0., 0., 1., 0., 3.,
        1., 0., 0., 0., 3., 3., 3.]),
 array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., 53.]),
 array([6., 2., 5., 3., 2., 3., 2., 2., 0., 2., 5., 9., 4.]))

In [8]:
env[0:56]

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6.])

In [9]:
env[57],env[72],env[67],env[74]

(3.0, 3.0, 3.0, 3.0)

In [10]:
env[69:72]

array([0., 0., 0.])

In [11]:
for i in range(5):
    if np.where(env[0:56]==i)[0].shape[0]>0:
        print(visualCard(np.where(env[0:56]==i)[0]))

In [12]:
env,draw_pile,discard_pile = stepEnv(env,draw_pile,discard_pile,0)

IndexError: list index out of range

In [ ]:
getValidActions(getAgentState(env,draw_pile,discard_pile))

In [ ]:
env[72]

In [ ]:
env[67],env[57]

In [13]:
from env import *

In [14]:
def random_player2(state,per):
    list_action  = np.where(getValidActions(state)==1)[0]
    action = np.random.choice(list_action)
    print(list_action)
    return action,per

In [15]:
main([random_player2]*5,1,0)

[3 6 7]
[ 0 10]
[ 0 10]
[3 6]
[11 12 13 14]
[15 26]
[6]
[1 3 6]
[ 0 10]
[2 3 4 6]
[ 0 10]
[11 12 13 14]
[18 22 23 26]
[2 4 6 7]
[1 6]
[ 0 10]
[2 3 6]
[5 6]
[6]
[3 6]
[2 4 6 7 9]
[ 0 10]
[2 6 7]
[ 0 10]
[11 12 13 14]
[2 6]
[6]
[2 3 5 6 9]
[6 7]
[11 12 13 14]
[6]
[3 4 6]
[2 6 7]
[ 0 10]
[11 12 13 14]
[6 7]
[ 0 10]
[11 12 13 14]
[6]
[6]
[1 2 3 5 6 9]
[ 0 10]
[11 12 13 14]
[19 23 24 26]
[1 2 5 6 9]
[ 0 10]
[39 40 41 42 43 44 45 46 47 48 49 50]
[6]
[6]
[3 4 6]
[ 0 10]
[10]
[4 6]
[6]
[6]
[4 6]
[6]
[6]
[6]
[5 6]
[6]
[5 6]
[6 7]
[11 12 14]
[6]
[6 7]
[6]
[4 5 6]
[6]
[6 7]
[11 13 14]
[6]
[2 6]
[4 5 6]
[5 6]
[6]
[1 2 6]
[4 5 6]


(array([0, 1, 0, 0, 0, 0]), 0)